[project]
name = "ollama-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "googlesearch-python>=1.3.0",
    "ollama>=0.4.7",
    "requests>=2.32.3",
]
