[project]
name = "api-group"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.16",
    "beautifulsoup4>=4.13.3",
    "bilibili-api-python>=17.1.4",
    "googlesearch-python>=1.3.0",
]
